from django.urls import path
from . import views

urlpatterns = [
    path(
        '',
        views.index,
        name='home'
    ),
    path(
        'about/',
        views.about,
        name='about'
    ),
    path(
        'wear/',
        views.wear,
        name='wear'
    ),
    path(
        'accessories/',
        views.accessories,
        name='accessories'
    ),
    path(
        'promo/',
        views.promo,
        name='promo'
    ),
    path(
        '<int:pk>',
        views.ItemsDetailView.as_view(),
        name='item-page'
    ),
    path(
        'add/<int:pk>/',
        views.add_to_order,
        name='add_to_order'
    ),
    path(
        'privacy_policy/',
        views.privacy_policy,
        name='privacy_policy'
    ),
    path(
        'refund_and_exchange_policy/',
        views.refund_and_exchange_policy,
        name='refund_and_exchange_policy'
    ),
    path(
        'public_offer/',
        views.public_offer,
        name='public_offer'
    ),
    path(
        'realization/',
        views.realization_request,
        name='realization_request'
    ),
    path(
        'rental/',
        views.rental_request,
        name='rental_request'
    ),
    path(
        'partners_page/',
        views.partners_page,
        name='partners_page'
    ),
    path(
        'form_other/',
        views.other_request,
        name='other_request'
    ),
]
